apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: three-tier
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
  type: ClusterIP  # Internal Service, as Ingress will expose it

