apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: three-tier
spec:
  selector:
    app: backend  # Matches the backend deployment label
  ports:
    - protocol: TCP
      port: 3500        # Service exposed port inside cluster
  type: ClusterIP  # Internal access only (used by frontend)

