apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: three-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: public.ecr.aws/g8o0v1p2/three-tier-backend:latest  # Replace with your actual image
          ports:
            - containerPort: 3500
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret  # Corrected to use database-secret
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret  # Corrected to use database-secret
                  key: MONGO_PASSWORD
            - name: MONGO_CONN_STR
              value: "mongodb://mongodb-service:27017/todo"  # Directly using connection string

