apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app
  namespace: rbac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      serviceAccountName: notes-app-sa  
      containers:
      - name: notes-app
        image: dev3103/notes-app:latest
        ports:
          - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"



