apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: rbac
  name: notes-app-rolebinding
subjects:
- kind: ServiceAccount
  name: notes-app-sa
  namespace: rbac
roleRef:
  kind: Role
  name: notes-app-role
  apiGroup: rbac.authorization.k8s.io

