apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
<<<<<<< HEAD
  namespace: hpa
=======
  namespace: rbac
>>>>>>> 589f2d1 (RBAC DONE)
spec:
  selector:
    app: notes-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

