apiVersion: v1
kind: Service
metadata:
  name: two-tier-app-service
  namespace: two-tier-app
spec:
  selector:
    app: two-tier-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
    
